apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-gallery
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-this-in-production-use-strong-key"
  DB_PASSWORD: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: django-gallery
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
